version: "3.9"

services:
    pwn_ubuntu1804:
        build:
            context: .
            args:
                UID: $UID
                GID: $GID
                USERNAME: $USERNAME
                GROUPNAME: $GROUPNAME
        user: $UID:$GID
        tty: true
        volumes:
            - ./Programs:/home/$USERNAME/pwn/Programs:rw
